name       : aubio
version    : 0.4.2
release    : 2
source     :
    - http://aubio.org/pub/aubio-0.4.2.tar.bz2 : 1cc58e0fed2b9468305b198ad06b889f228b797a082c2ede716dc30fcb4f8f1f
license    : GPL-3.0
component  : multimedia.library
summary    : Library for extracting annotations from audio signals.
description: |
    aubio is a tool designed for the extraction of annotations from audio signals. Its features include segmenting a sound file before each o its attacks, performing pitch detection, tapping the beat and producing MIDI streams from live audio.
builddeps  :
    - pkgconfig(jack)
    - pkgconfig(libavcodec)
    - pkgconfig(python-2.7)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
setup      : |
    ./waf configure --prefix=/usr --libdir=%libdir%
build      : |
    ./waf build
install    : |
    ./waf install --destdir="$installdir"
