name       : aubio
version    : 0.4.5
release    : 3
source     :
    - https://aubio.org/pub/aubio-0.4.5.tar.bz2 : 70c2804e6f4fbf0ebc0fb9ac8cc9d465ef4a4d438311c074c9a7364e98827af6
license    : GPL-3.0
component  : multimedia.library
summary    : Library for extracting annotations from audio signals.
description: |
    aubio is a tool designed for the extraction of annotations from audio signals. Its features include segmenting a sound file before each o its attacks, performing pitch detection, tapping the beat and producing MIDI streams from live audio.
builddeps  :
    - pkgconfig(fftw3f)
    - pkgconfig(libavcodec)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-creation-of-static-library.patch
    ./waf configure --prefix=/usr \
                    --libdir=%libdir% \
                    --enable-fftw3f
build      : |
    ./waf build
install    : |
    ./waf install --destdir="%installroot%"
