name       : aubio
version    : 0.4.6
release    : 4
source     :
    - https://aubio.org/pub/aubio-0.4.6.tar.bz2 : bdc73be1f007218d3ea6d2a503b38a217815a0e2ccc4ed441f6e850ed5d47cfb
license    : GPL-3.0-or-later
component  : multimedia.library
summary    : Library for extracting annotations from audio signals
description: |
    aubio is a tool designed for the extraction of annotations from audio signals. Its features include segmenting a sound file before each o its attacks, performing pitch detection, tapping the beat and producing MIDI streams from live audio.
builddeps  :
    - pkgconfig(fftw3f)
    - pkgconfig(libavcodec)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
setup      : |
    %waf_configure --enable-fftw3f
build      : |
    %waf_build
install    : |
    %waf_install
