name        : aubio
version     : 0.4.2
release     : 1
source      :
    - http://aubio.org/pub/aubio-0.4.2.tar.bz2 : 1cc58e0fed2b9468305b198ad06b889f228b797a082c2ede716dc30fcb4f8f1f
license     :
    - GPL
component   : multimedia.library
summary     : Library for extracting annotations from audio signals.
builddeps   :
    - python
description : |
    aubio is a tool designed for the extraction of annotations from audio signals. Its features include segmenting a sound file before each o its attacks, performing pitch detection, tapping the beat and producing MIDI streams from live audio.
setup       : |
    # waf doesn't have --build
    OPTS="$(echo $CONFOPTS | sed -E 's/--build=[a-z0-9_\-]+ //')"
    %workdir%/waf configure $OPTS 
build       : |
    %workdir%/waf build %JOBS%
install     : |
    %workdir%/waf install --destdir="$installdir"
